name: Dongs
main: me.anuw.anuwPlugin.Main
version: 1.0.0
description: Adds dongs and dong functionalities
api-version: 1.13
author: anuw
commands:
  oop:
    description: Panic switch. Toggles plugin functionality
  dong:
    description: Adds/removes/changes player dong
    usage: (Argument optional) /dong <item_name>
  nut:
    description: Stream of white particles controlled with cursor
    usage: (All arguments optional) /nut <strength> <duration> <load> <playername>
  piss:
    description: Stream of water particles controlled with cursor
    usage: (All arguments optional) /piss <strength> <duration> <load> <playername>